{% set name = "ccartogram" %}
{% set version = "0.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/benmaier/cCartogram/archive/refs/tags/v{{ version }}.tar.gz
  # sha256: UPDATE_WITH_ACTUAL_SHA256_AFTER_TAGGING_RELEASE

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools >=61
    - pybind11 >=2.10
    - fftw
  run:
    - python
    - fftw

test:
  imports:
    - cCartogram
  commands:
    - python -c "import cCartogram; print('cCartogram imported successfully')"

about:
  home: https://github.com/benmaier/cCartogram
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python wrapper for Mark Newman's density-equalizing cartogram algorithm
  description: |
    cCartogram is a Python wrapper for Mark Newman's C implementation
    of the density-equalizing cartogram algorithm. It uses FFTW for
    fast Fourier transforms.
  dev_url: https://github.com/benmaier/cCartogram

extra:
  recipe-maintainers:
    - benmaier
